services:
  backend:
    build:
      context: ./backend
    container_name: filmedin-backend
    environment:
      PORT: 5000
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      RESEND_API_KEY: ${RESEND_API_KEY}
      TMDB_API_KEY: ${VITE_TMDB_API_KEY}
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_TMDB_API_KEY: ${VITE_TMDB_API_KEY}
    container_name: filmedin-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: unless-stopped
